// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iOneDataGrove.Persistence.Data;

#nullable disable

namespace iOneDataGrove.Persistence.Migrations
{
    [DbContext(typeof(IOneDataGroveDbContext))]
    [Migration("20260817124559_BaselineExistingSchema")]
    partial class BaselineExistingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.Commit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int?>("Additions")
                        .HasColumnType("integer")
                        .HasColumnName("additions");

                    b.Property<string>("AuthorEmail")
                        .HasColumnType("text")
                        .HasColumnName("author_email");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text")
                        .HasColumnName("author_name");

                    b.Property<long?>("AuthorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_user_id");

                    b.Property<DateTime?>("AuthoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authored_at");

                    b.Property<DateTime?>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<string>("CommitterEmail")
                        .HasColumnType("text")
                        .HasColumnName("committer_email");

                    b.Property<string>("CommitterName")
                        .HasColumnType("text")
                        .HasColumnName("committer_name");

                    b.Property<long?>("CommitterUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("committer_user_id");

                    b.Property<int?>("Deletions")
                        .HasColumnType("integer")
                        .HasColumnName("deletions");

                    b.Property<int?>("FilesChanged")
                        .HasColumnType("integer")
                        .HasColumnName("files_changed");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("text")
                        .HasColumnName("html_url");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("repository_id");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha");

                    b.Property<DateTime>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("commits_pkey");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("CommitterUserId");

                    b.HasIndex(new[] { "RepositoryId", "CommittedAt" }, "ix_github_commits_repository_committed");

                    b.HasIndex(new[] { "RepositoryId", "Sha" }, "uq_github_commits_repository_sha")
                        .IsUnique();

                    b.ToTable("commits", "github");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.CommitFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int?>("Additions")
                        .HasColumnType("integer")
                        .HasColumnName("additions");

                    b.Property<int?>("Changes")
                        .HasColumnType("integer")
                        .HasColumnName("changes");

                    b.Property<long>("CommitId")
                        .HasColumnType("bigint")
                        .HasColumnName("commit_id");

                    b.Property<int?>("Deletions")
                        .HasColumnType("integer")
                        .HasColumnName("deletions");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("Patch")
                        .HasColumnType("text")
                        .HasColumnName("patch");

                    b.Property<string>("PreviousFilename")
                        .HasColumnType("text")
                        .HasColumnName("previous_filename");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("commit_files_pkey");

                    b.HasIndex(new[] { "Filename" }, "ix_github_commit_files_filename");

                    b.HasIndex(new[] { "CommitId", "Filename" }, "uq_github_commit_files_commit_filename")
                        .IsUnique();

                    b.ToTable("commit_files", "github");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long?>("AuthorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<long?>("ClosedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("closed_by_user_id");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("integer")
                        .HasColumnName("comments_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GithubId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_id");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("text")
                        .HasColumnName("html_url");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean")
                        .HasColumnName("locked");

                    b.Property<string>("NodeId")
                        .HasColumnType("text")
                        .HasColumnName("node_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("repository_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("StateReason")
                        .HasColumnType("text")
                        .HasColumnName("state_reason");

                    b.Property<DateTime>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("issues_pkey");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex(new[] { "RepositoryId" }, "ix_github_issues_repository");

                    b.HasIndex(new[] { "RepositoryId", "UpdatedAt" }, "ix_github_issues_repository_updated");

                    b.HasIndex(new[] { "UpdatedAt" }, "ix_github_issues_updated_at");

                    b.HasIndex(new[] { "GithubId" }, "uq_github_issues_github_id")
                        .IsUnique();

                    b.HasIndex(new[] { "RepositoryId", "Number" }, "uq_github_issues_repository_number")
                        .IsUnique();

                    b.ToTable("issues", "github");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.IssueComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthorAssociation")
                        .HasColumnType("text")
                        .HasColumnName("author_association");

                    b.Property<long?>("AuthorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GithubId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_id");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("text")
                        .HasColumnName("html_url");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<string>("NodeId")
                        .HasColumnType("text")
                        .HasColumnName("node_id");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("repository_id");

                    b.Property<DateTime>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("issue_comments_pkey");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex(new[] { "IssueId" }, "ix_github_issue_comments_issue");

                    b.HasIndex(new[] { "UpdatedAt" }, "ix_github_issue_comments_updated");

                    b.HasIndex(new[] { "GithubId" }, "uq_github_issue_comments_github_id")
                        .IsUnique();

                    b.ToTable("issue_comments", "github");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.PullRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int?>("Additions")
                        .HasColumnType("integer")
                        .HasColumnName("additions");

                    b.Property<long?>("AuthorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_user_id");

                    b.Property<string>("BaseBranch")
                        .HasColumnType("text")
                        .HasColumnName("base_branch");

                    b.Property<string>("BaseSha")
                        .HasColumnType("text")
                        .HasColumnName("base_sha");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int?>("ChangedFiles")
                        .HasColumnType("integer")
                        .HasColumnName("changed_files");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int?>("CommitsCount")
                        .HasColumnType("integer")
                        .HasColumnName("commits_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Deletions")
                        .HasColumnType("integer")
                        .HasColumnName("deletions");

                    b.Property<long>("GithubId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_id");

                    b.Property<string>("HeadBranch")
                        .HasColumnType("text")
                        .HasColumnName("head_branch");

                    b.Property<string>("HeadSha")
                        .HasColumnType("text")
                        .HasColumnName("head_sha");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("text")
                        .HasColumnName("html_url");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean")
                        .HasColumnName("locked");

                    b.Property<string>("MergeCommitSha")
                        .HasColumnType("text")
                        .HasColumnName("merge_commit_sha");

                    b.Property<bool>("Merged")
                        .HasColumnType("boolean")
                        .HasColumnName("merged");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("merged_at");

                    b.Property<long?>("MergedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("merged_by_user_id");

                    b.Property<string>("NodeId")
                        .HasColumnType("text")
                        .HasColumnName("node_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("repository_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pull_requests_pkey");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("MergedByUserId");

                    b.HasIndex(new[] { "RepositoryId" }, "ix_github_pull_requests_repository");

                    b.HasIndex(new[] { "UpdatedAt" }, "ix_github_pull_requests_updated");

                    b.HasIndex(new[] { "GithubId" }, "uq_github_pull_requests_github_id")
                        .IsUnique();

                    b.HasIndex(new[] { "RepositoryId", "Number" }, "uq_github_pull_requests_repository_number")
                        .IsUnique();

                    b.ToTable("pull_requests", "github");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.PullRequestCommit", b =>
                {
                    b.Property<long>("PullRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("pull_request_id");

                    b.Property<long>("CommitId")
                        .HasColumnType("bigint")
                        .HasColumnName("commit_id");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("PullRequestId", "CommitId")
                        .HasName("pull_request_commits_pkey");

                    b.HasIndex("CommitId");

                    b.ToTable("pull_request_commits", "github");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.PullRequestFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int?>("Additions")
                        .HasColumnType("integer")
                        .HasColumnName("additions");

                    b.Property<int?>("Changes")
                        .HasColumnType("integer")
                        .HasColumnName("changes");

                    b.Property<int?>("Deletions")
                        .HasColumnType("integer")
                        .HasColumnName("deletions");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("Patch")
                        .HasColumnType("text")
                        .HasColumnName("patch");

                    b.Property<string>("PreviousFilename")
                        .HasColumnType("text")
                        .HasColumnName("previous_filename");

                    b.Property<long>("PullRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pull_request_files_pkey");

                    b.HasIndex(new[] { "Filename" }, "ix_github_pr_files_filename");

                    b.HasIndex(new[] { "PullRequestId", "Filename" }, "uq_github_pr_files_pr_filename")
                        .IsUnique();

                    b.ToTable("pull_request_files", "github");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.Repository", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBranch")
                        .HasColumnType("text")
                        .HasColumnName("default_branch");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<long>("GithubId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_id");

                    b.Property<string>("HtmlUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_url");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<bool>("IsFork")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fork");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NodeId")
                        .HasColumnType("text")
                        .HasColumnName("node_id");

                    b.Property<long?>("OwnerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PrimaryLanguage")
                        .HasColumnType("text")
                        .HasColumnName("primary_language");

                    b.Property<DateTime?>("PushedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pushed_at");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<DateTime>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("repositories_pkey");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex(new[] { "FullName" }, "uq_github_repositories_full_name")
                        .IsUnique();

                    b.HasIndex(new[] { "GithubId" }, "uq_github_repositories_github_id")
                        .IsUnique();

                    b.ToTable("repositories", "github");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.SyncRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("ItemsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("items_failed");

                    b.Property<int>("ItemsInserted")
                        .HasColumnType("integer")
                        .HasColumnName("items_inserted");

                    b.Property<int>("ItemsRead")
                        .HasColumnType("integer")
                        .HasColumnName("items_read");

                    b.Property<int>("ItemsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("items_updated");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<long?>("RepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("repository_id");

                    b.Property<string>("ResourceType")
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sync_type");

                    b.HasKey("Id")
                        .HasName("sync_runs_pkey");

                    b.HasIndex("RepositoryId");

                    b.ToTable("sync_runs", "ingestion");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.SyncState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BackfillFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("backfill_from");

                    b.Property<DateTime?>("BackfillTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("backfill_to");

                    b.Property<string>("Cursor")
                        .HasColumnType("text")
                        .HasColumnName("cursor");

                    b.Property<DateTime?>("LastGithubUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_github_updated_at");

                    b.Property<DateTime?>("LastSuccessfulSync")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_sync");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("repository_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("sync_state_pkey");

                    b.HasIndex(new[] { "RepositoryId", "ResourceType" }, "uq_sync_state_repository_resource")
                        .IsUnique();

                    b.ToTable("sync_state", "ingestion");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<long>("GithubId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_id");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("text")
                        .HasColumnName("html_url");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NodeId")
                        .HasColumnType("text")
                        .HasColumnName("node_id");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<bool?>("SiteAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("site_admin");

                    b.Property<DateTime>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserType")
                        .HasColumnType("text")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "GithubId" }, "uq_github_users_github_id")
                        .IsUnique();

                    b.ToTable("users", "github");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.Commit", b =>
                {
                    b.HasOne("iOneDataGrove.Persistence.Entities.User", "AuthorUser")
                        .WithMany("CommitAuthorUsers")
                        .HasForeignKey("AuthorUserId")
                        .HasConstraintName("commits_author_user_id_fkey");

                    b.HasOne("iOneDataGrove.Persistence.Entities.User", "CommitterUser")
                        .WithMany("CommitCommitterUsers")
                        .HasForeignKey("CommitterUserId")
                        .HasConstraintName("commits_committer_user_id_fkey");

                    b.HasOne("iOneDataGrove.Persistence.Entities.Repository", "Repository")
                        .WithMany("Commits")
                        .HasForeignKey("RepositoryId")
                        .IsRequired()
                        .HasConstraintName("commits_repository_id_fkey");

                    b.Navigation("AuthorUser");

                    b.Navigation("CommitterUser");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.CommitFile", b =>
                {
                    b.HasOne("iOneDataGrove.Persistence.Entities.Commit", "Commit")
                        .WithMany("CommitFiles")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("commit_files_commit_id_fkey");

                    b.Navigation("Commit");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.Issue", b =>
                {
                    b.HasOne("iOneDataGrove.Persistence.Entities.User", "AuthorUser")
                        .WithMany("IssueAuthorUsers")
                        .HasForeignKey("AuthorUserId")
                        .HasConstraintName("issues_author_user_id_fkey");

                    b.HasOne("iOneDataGrove.Persistence.Entities.User", "ClosedByUser")
                        .WithMany("IssueClosedByUsers")
                        .HasForeignKey("ClosedByUserId")
                        .HasConstraintName("issues_closed_by_user_id_fkey");

                    b.HasOne("iOneDataGrove.Persistence.Entities.Repository", "Repository")
                        .WithMany("Issues")
                        .HasForeignKey("RepositoryId")
                        .IsRequired()
                        .HasConstraintName("issues_repository_id_fkey");

                    b.Navigation("AuthorUser");

                    b.Navigation("ClosedByUser");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.IssueComment", b =>
                {
                    b.HasOne("iOneDataGrove.Persistence.Entities.User", "AuthorUser")
                        .WithMany("IssueComments")
                        .HasForeignKey("AuthorUserId")
                        .HasConstraintName("issue_comments_author_user_id_fkey");

                    b.HasOne("iOneDataGrove.Persistence.Entities.Issue", "Issue")
                        .WithMany("IssueComments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("issue_comments_issue_id_fkey");

                    b.HasOne("iOneDataGrove.Persistence.Entities.Repository", "Repository")
                        .WithMany("IssueComments")
                        .HasForeignKey("RepositoryId")
                        .IsRequired()
                        .HasConstraintName("issue_comments_repository_id_fkey");

                    b.Navigation("AuthorUser");

                    b.Navigation("Issue");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.PullRequest", b =>
                {
                    b.HasOne("iOneDataGrove.Persistence.Entities.User", "AuthorUser")
                        .WithMany("PullRequestAuthorUsers")
                        .HasForeignKey("AuthorUserId")
                        .HasConstraintName("pull_requests_author_user_id_fkey");

                    b.HasOne("iOneDataGrove.Persistence.Entities.User", "MergedByUser")
                        .WithMany("PullRequestMergedByUsers")
                        .HasForeignKey("MergedByUserId")
                        .HasConstraintName("pull_requests_merged_by_user_id_fkey");

                    b.HasOne("iOneDataGrove.Persistence.Entities.Repository", "Repository")
                        .WithMany("PullRequests")
                        .HasForeignKey("RepositoryId")
                        .IsRequired()
                        .HasConstraintName("pull_requests_repository_id_fkey");

                    b.Navigation("AuthorUser");

                    b.Navigation("MergedByUser");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.PullRequestCommit", b =>
                {
                    b.HasOne("iOneDataGrove.Persistence.Entities.Commit", "Commit")
                        .WithMany("PullRequestCommits")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pull_request_commits_commit_id_fkey");

                    b.HasOne("iOneDataGrove.Persistence.Entities.PullRequest", "PullRequest")
                        .WithMany("PullRequestCommits")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pull_request_commits_pull_request_id_fkey");

                    b.Navigation("Commit");

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.PullRequestFile", b =>
                {
                    b.HasOne("iOneDataGrove.Persistence.Entities.PullRequest", "PullRequest")
                        .WithMany("PullRequestFiles")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pull_request_files_pull_request_id_fkey");

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.Repository", b =>
                {
                    b.HasOne("iOneDataGrove.Persistence.Entities.User", "OwnerUser")
                        .WithMany("Repositories")
                        .HasForeignKey("OwnerUserId")
                        .HasConstraintName("repositories_owner_user_id_fkey");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.SyncRun", b =>
                {
                    b.HasOne("iOneDataGrove.Persistence.Entities.Repository", "Repository")
                        .WithMany("SyncRuns")
                        .HasForeignKey("RepositoryId")
                        .HasConstraintName("sync_runs_repository_id_fkey");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.SyncState", b =>
                {
                    b.HasOne("iOneDataGrove.Persistence.Entities.Repository", "Repository")
                        .WithMany("SyncStates")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sync_state_repository_id_fkey");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.Commit", b =>
                {
                    b.Navigation("CommitFiles");

                    b.Navigation("PullRequestCommits");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.Issue", b =>
                {
                    b.Navigation("IssueComments");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.PullRequest", b =>
                {
                    b.Navigation("PullRequestCommits");

                    b.Navigation("PullRequestFiles");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.Repository", b =>
                {
                    b.Navigation("Commits");

                    b.Navigation("IssueComments");

                    b.Navigation("Issues");

                    b.Navigation("PullRequests");

                    b.Navigation("SyncRuns");

                    b.Navigation("SyncStates");
                });

            modelBuilder.Entity("iOneDataGrove.Persistence.Entities.User", b =>
                {
                    b.Navigation("CommitAuthorUsers");

                    b.Navigation("CommitCommitterUsers");

                    b.Navigation("IssueAuthorUsers");

                    b.Navigation("IssueClosedByUsers");

                    b.Navigation("IssueComments");

                    b.Navigation("PullRequestAuthorUsers");

                    b.Navigation("PullRequestMergedByUsers");

                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
